import fs from "fs";
import { describe, expect, it } from "vitest";
import { main } from "./part-1";

const exampleInput = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

describe("Day 8 Part 1", () => {
  describe("Test the global main function", () => {
    it("should return 14", async () => {
      const result = await main(exampleInput);
      expect(result).toBe(14);
    });
  });
});
